### ISSUE TITLE
Compatibility with ConfigurableCompany (and maybe other mods)

### ISSUE THREAD

**Issue by TheAnsuz** [paul-merkamp/LCBetterSaves#20] opened 2024-01-21 22:48 UTC
Good afternoon.

I wanted to contact with the author of better saves for what I found that may cause compatibility issues with ConfigurableCompany and any mod that adds files to the game's directory.

In this case for what I've seen, BetterSaves uses the name of the files to check if it's a save-file, however this method may fail as many mods (including ConfigurableCompany) append a suffix to those mentioned saves, thus causing BetterSaves to think that a file called _LCSaveFile4**SOMETHING**_ is a save file, wich it isn't.

This in fact may even happen if a user has any other file (for example, a backup file) that also starts by `LCSaveFile`.

I would love to help with the issue and, as the ConfigurableCompany developer, determine what's necesary to have between mod's compatibility.

For what I could check in the source, I think changes should be done under the `CountSaveFiles()` method.

**Comment by paul-merkamp** [comment] 2024-01-21 23:01
closing, essentially a duplicate of #18. ConfigurableCompany is likely a legitimate case of not being able to embed mod data directly in the save file. working on a fix for the issue itself now

**Closed by paul-merkamp** 2024-01-21 23:01 UTC
